export const questions = [
  {
    id: 1,
    text: { en: 'What is the primary purpose of multi-factor authentication?', bg: 'Каква е основната цел на многофакторната автентикация?' },
    options: {
      en: ['To make passwords shorter', 'To add independent layers of identity verification', 'To store passwords in the browser', 'To avoid software updates'],
      bg: ['Да направи паролите по-кратки', 'Да добави независими нива за проверка на самоличността', 'Да съхранява паролите в браузъра', 'Да избегне софтуерните обновявания'],
    },
    correct: 1,
    explanation: { en: 'MFA requires two or more independent factors, so a stolen password alone is not enough to access an account.', bg: 'MFA изисква два или повече независими фактора, така че открадната парола сама по себе си не е достатъчна за достъп.' },
  },
  {
    id: 2,
    text: { en: 'Which password is the strongest?', bg: 'Коя парола е най-сигурна?' },
    options: { en: ['Sofia2026', 'Password!1', 'blue-train-copper-orbit-47', '123456789'], bg: ['Sofia2026', 'Password!1', 'blue-train-copper-orbit-47', '123456789'] },
    correct: 2,
    explanation: { en: 'A long, unique passphrase is harder to guess or brute-force than short, predictable passwords.', bg: 'Дългата и уникална фраза е по-трудна за отгатване или разбиване от кратките и предвидими пароли.' },
  },
  {
    id: 3,
    text: { en: 'What should you do first after receiving a suspicious email?', bg: 'Какво трябва да направите първо при съмнителен имейл?' },
    options: { en: ['Click the link to inspect it', 'Reply and ask who sent it', 'Verify the sender through a separate trusted channel', 'Forward it to colleagues'], bg: ['Да натиснете линка, за да го проверите', 'Да отговорите и да попитате кой го е изпратил', 'Да проверите подателя чрез отделен доверен канал', 'Да го препратите на колеги'] },
    correct: 2,
    explanation: { en: 'Do not interact with suspicious content. Confirm the request through a known phone number, website, or contact.', bg: 'Не взаимодействайте със съмнително съдържание. Потвърдете заявката чрез познат телефон, сайт или контакт.' },
  },
  {
    id: 4,
    text: { en: 'Why are software updates important?', bg: 'Защо софтуерните обновявания са важни?' },
    options: { en: ['They only change the design', 'They often patch security vulnerabilities', 'They remove all passwords', 'They make backups unnecessary'], bg: ['Променят само дизайна', 'Често отстраняват уязвимости в сигурността', 'Премахват всички пароли', 'Правят архивите ненужни'] },
    correct: 1,
    explanation: { en: 'Updates frequently include fixes for known security flaws that attackers may otherwise exploit.', bg: 'Обновяванията често включват поправки на известни пропуски, които нападатели могат да използват.' },
  },
  {
    id: 5,
    text: { en: 'What is the safest way to use public Wi-Fi?', bg: 'Кой е най-безопасният начин за използване на обществен Wi-Fi?' },
    options: { en: ['Share files with everyone', 'Use a trusted VPN and avoid sensitive actions', 'Disable device security', 'Connect to any similarly named network'], bg: ['Да споделяте файлове с всички', 'Да използвате доверен VPN и да избягвате чувствителни действия', 'Да изключите защитата на устройството', 'Да се свържете към всяка мрежа с подобно име'] },
    correct: 1,
    explanation: { en: 'A trusted VPN encrypts traffic. Sensitive transactions are still best avoided on networks you do not control.', bg: 'Довереният VPN криптира трафика. Все пак е най-добре да избягвате чувствителни операции в чужди мрежи.' },
  },
  {
    id: 6,
    text: { en: 'What does the principle of least privilege mean?', bg: 'Какво означава принципът за минимални права?' },
    options: { en: ['Everyone gets administrator access', 'Users receive only the access needed for their work', 'Access is never reviewed', 'Passwords are shared within teams'], bg: ['Всеки получава администраторски достъп', 'Потребителите получават само нужния за работата им достъп', 'Достъпът никога не се преглежда', 'Паролите се споделят в екипа'] },
    correct: 1,
    explanation: { en: 'Limiting access reduces both accidental damage and the impact of a compromised account.', bg: 'Ограничаването на достъпа намалява както случайните щети, така и ефекта от компрометиран профил.' },
  },
  {
    id: 7,
    text: { en: 'Which backup strategy is generally recommended?', bg: 'Коя стратегия за архивиране обикновено се препоръчва?' },
    options: { en: ['One copy on your laptop', 'The 3-2-1 rule', 'No backup for cloud files', 'A yearly USB copy only'], bg: ['Едно копие на лаптопа', 'Правилото 3-2-1', 'Без архив за облачни файлове', 'Само едно годишно копие на USB'] },
    correct: 1,
    explanation: { en: 'The 3-2-1 rule means three copies, on two media types, with one copy stored off-site.', bg: 'Правилото 3-2-1 означава три копия, на два вида носители, като едно е на друго място.' },
  },
  {
    id: 8,
    text: { en: 'What is phishing?', bg: 'Какво е фишинг?' },
    options: { en: ['A hardware upgrade', 'A fraudulent attempt to steal information or trigger an action', 'A data compression method', 'A secure login standard'], bg: ['Хардуерно обновяване', 'Измамен опит за кражба на информация или предизвикване на действие', 'Метод за компресиране на данни', 'Стандарт за сигурно влизане'] },
    correct: 1,
    explanation: { en: 'Phishing impersonates a trusted person or organization to manipulate you into revealing data or taking an unsafe action.', bg: 'Фишингът имитира доверен човек или организация, за да ви подведе да разкриете данни или да извършите опасно действие.' },
  },
  {
    id: 9,
    text: { en: 'How should confidential paper documents be discarded?', bg: 'Как трябва да се изхвърлят поверителни документи на хартия?' },
    options: { en: ['In a regular bin', 'By shredding them securely', 'On a public desk', 'After photographing them'], bg: ['В обикновен кош', 'Чрез сигурно унищожаване с шредер', 'На обществено бюро', 'След като бъдат снимани'] },
    correct: 1,
    explanation: { en: 'Secure shredding prevents sensitive information from being recovered from discarded documents.', bg: 'Сигурното унищожаване не позволява чувствителната информация да бъде възстановена от изхвърлените документи.' },
  },
  {
    id: 10,
    text: { en: 'Who is responsible for information security in an organization?', bg: 'Кой носи отговорност за информационната сигурност в организацията?' },
    options: { en: ['Only the IT team', 'Only management', 'Every person who handles information', 'Only external auditors'], bg: ['Само IT екипът', 'Само ръководството', 'Всеки, който работи с информация', 'Само външните одитори'] },
    correct: 2,
    explanation: { en: 'Security is a shared responsibility: every person’s decisions can protect or expose organizational information.', bg: 'Сигурността е споделена отговорност: решенията на всеки могат да защитят или изложат информацията на риск.' },
  },
];
